# Generated by Django 2.1.1 on 2019-10-31 08:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adonator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('adonator_galery', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdonatorGalery'))),
                ('address', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Address'))),
                ('cpf', models.CharField(default=None, max_length=200, null=True)),
                ('cnpj', models.CharField(default=None, max_length=200, null=True)),
                ('birth_date', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Adonator',
                'verbose_name_plural': 'Adonators',
                'db_table': 'adonator',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.IntegerField(blank=True, default=None, null=True)),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AdonatorGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adonator', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adonator'))),
                ('photo', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AdonatorGalery',
                'verbose_name_plural': 'AdonatorsGaleries',
                'db_table': 'adonator_galery',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adonater', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adonater'))),
                ('item_type_tag', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tag'))),
                ('purpose_tag', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tag'))),
                ('campaign_galery', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CampaignGalery'))),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('photos', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CampaignGalery',
                'verbose_name_plural': 'CampaignsGaleries',
                'db_table': 'campaign_galery',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adonator', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adonator'))),
                ('item', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Item'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaingn', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('donation', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donation'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'DonationCampaign',
                'verbose_name_plural': 'DonationsCampaigns',
                'db_table': 'donation_campaign',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_galery', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ItemGalery'))),
                ('name', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('coments', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Item'))),
                ('photo', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ItemGalery',
                'verbose_name_plural': 'ItemsGaleries',
                'db_table': 'item_galery',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adonater', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adonater'))),
                ('campaign', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
    ]
