# Generated by Django 2.2.7 on 2019-11-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191113_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('PORUPUSE', 'pourpuse'), ('ITEM', 'item')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TagCampaign',
        ),
    ]
