# Generated by Django 2.2.7 on 2019-11-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191113_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigngalery',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigngalery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='itemgalery',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemgalery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tag',
        ),
        migrations.AddField(
            model_name='photo',
            name='adonator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Campaign'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdonatorGalery',
        ),
        migrations.DeleteModel(
            name='CampaignGalery',
        ),
        migrations.DeleteModel(
            name='ItemGalery',
        ),
    ]
