# Generated by Django 2.2.7 on 2019-11-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191113_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='app.Campaign'),
        ),
    ]
