# Generated by Django 2.2.7 on 2019-11-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191114_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngalery',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_photo', to='app.Photo'),
        ),
    ]
