# Generated by Django 2.2.7 on 2019-11-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191114_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdonatorPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('adonator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adonator_photo', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_adonator', to='app.Photo')),
            ],
            options={
                'verbose_name': 'AdonatorPhoto',
                'verbose_name_plural': 'AdonatorPhotos',
                'db_table': 'adonator_photo',
            },
        ),
        migrations.CreateModel(
            name='CampaignPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camapaign_photo', to='app.Campaign')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_campaign', to='app.Photo')),
            ],
            options={
                'verbose_name': 'CampaignPhoto',
                'verbose_name_plural': 'CampaignPhotos',
                'db_table': 'campaign_photo',
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_photo', to='app.Item')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_item', to='app.Photo')),
            ],
            options={
                'verbose_name': 'ItemPhoto',
                'verbose_name_plural': 'ItemPhotos',
                'db_table': 'item_photo',
            },
        ),
        migrations.CreateModel(
            name='TagCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_campaign', to='app.Campaign')),
            ],
            options={
                'verbose_name': 'TagCampaign',
                'verbose_name_plural': 'TagCampaigns',
                'db_table': 'tag_campaign',
            },
        ),
        migrations.RemoveField(
            model_name='campaigngalery',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigngalery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='itemgalery',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemgalery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='AdonatorGalery',
        ),
        migrations.DeleteModel(
            name='CampaignGalery',
        ),
        migrations.DeleteModel(
            name='ItemGalery',
        ),
        migrations.AddField(
            model_name='tagcampaign',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='app.Tag'),
        ),
    ]
