# Generated by Django 2.2.6 on 2019-10-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField()),
                ('item_type_tag_id', models.IntegerField()),
                ('purpose_tag_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('img_path', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField()),
                ('items_id', models.IntegerField()),
            ],
            options={
                'db_table': 'donations',
            },
        ),
        migrations.CreateModel(
            name='DonationsCampaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaingns_id', models.IntegerField()),
                ('donations_id', models.IntegerField()),
            ],
            options={
                'db_table': 'donations_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
                ('coments', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField()),
                ('campaigns_id', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
