# Generated by Django 2.2.6 on 2019-10-23 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adonate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User'))),
                ('item_type_tag_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tag'))),
                ('purpose_tag_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tag'))),
                ('campaigns_galeries_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CampaignGalery'))),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaigns_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('photos_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'campaign_galery',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User'))),
                ('items_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Item'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaingns_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('donations_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donation'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donation_campaign',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items_galeries_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ItemGalery'))),
                ('name', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('coments', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Item'))),
                ('photos_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'item_galery',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User'))),
                ('campaigns_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Campaign'))),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_galeries_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserGalerie'))),
                ('addresses_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Address'))),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cpf', models.CharField(default=None, max_length=200, null=True)),
                ('cnpj', models.CharField(default=None, max_length=200, null=True)),
                ('birth_date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User'))),
                ('photos_id', models.IntegerField(default=None, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Photo'))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_galery',
            },
        ),
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.DeleteModel(
            name='Campaigns',
        ),
        migrations.DeleteModel(
            name='CampaignsGaleries',
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
        migrations.DeleteModel(
            name='DonationsCampaigns',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='ItemsGaleries',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UsersGaleries',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
