version: "3.8"

services:
  web:
    build: ./src
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=adonate

volumes:
  postgres_data:
