# Generated by Django 2.1.1 on 2019-11-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adonator',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
