# Generated by Django 2.2.7 on 2019-11-14 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191114_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='adonator',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
        migrations.CreateModel(
            name='ItemGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='app.Item')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Photo')),
            ],
            options={
                'verbose_name': 'ItemGalery',
                'verbose_name_plural': 'ItemGaleries',
                'db_table': 'item_galery',
            },
        ),
        migrations.CreateModel(
            name='CampaignGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camapaign', to='app.Campaign')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Photo')),
            ],
            options={
                'verbose_name': 'CampaignGalery',
                'verbose_name_plural': 'CampaignGaleries',
                'db_table': 'campaign_galery',
            },
        ),
        migrations.CreateModel(
            name='AdonatorGalery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('adonator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adonator', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Photo')),
            ],
            options={
                'verbose_name': 'AdonatorGalery',
                'verbose_name_plural': 'AdonatorGaleries',
                'db_table': 'adonator_galery',
            },
        ),
    ]
