# Generated by Django 2.2.7 on 2019-11-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191114_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngalery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camapaign_galery', to='app.Campaign'),
        ),
    ]
